spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    data:
      classpath : data-h2.sql # 시작 시 실행할 script
    jpa:
      show-sql: true
      hibernate:
        ddl-auto : create-drop
      h2:
        console:
          enabled: true
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

